version: 2

project_name: mqtt

before:
  hooks:
    - go mod download

builds:
  - id: mqtt
    main: ./cmd/mqtt
    binary: mqtt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.revision={{ .Commit }}

archives:
  - ids:
      - mqtt
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  disable: true

dockers:
  - ids:
      - mqtt
    dockerfile: package/Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/jsirianni/mqtt:{{ .Version }}-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Lightweight MQTT broker
      - --label=org.opencontainers.image.url=https://github.com/jsirianni/mqtt
      - --label=org.opencontainers.image.source=https://github.com/jsirianni/mqtt
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.created={{ .Date }}
  - ids:
      - mqtt
    dockerfile: package/Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/jsirianni/mqtt:{{ .Version }}-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Lightweight MQTT broker
      - --label=org.opencontainers.image.url=https://github.com/jsirianni/mqtt
      - --label=org.opencontainers.image.source=https://github.com/jsirianni/mqtt
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.created={{ .Date }}

docker_manifests:
  - name_template: ghcr.io/jsirianni/mqtt:{{ .Version }}
    image_templates:
      - ghcr.io/jsirianni/mqtt:{{ .Version }}-amd64
      - ghcr.io/jsirianni/mqtt:{{ .Version }}-arm64
