name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  revive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go from go.mod
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download modules
        run: go mod download

      - name: Run revive
        run: go tool revive -set_exit_status ./...
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go from go.mod
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download modules
        run: go mod download

      - name: Run gosec
        run: go tool gosec ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go from go.mod
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download modules
        run: go mod download

      - name: Run tests
        run: go test ./...
